### PR TITLE
fix: voting on several initiatives does not execute

### LINKED ISSUE #791: [UI] Voting on several initiatives does not execute
Image

### PR DESCRIPTION
**Pull request by danielattilasimon**
Fixes #791.

### CODE REVIEW

File: frontend/app/src/tx-flows/allocateVotingPower.tsx [hunk 1]
```diff
@@ -189,17 +189,25 @@ export const allocateVotingPower: FlowDeclaration<AllocateVotingPowerRequest> =
 
         const allocationArgs = {
           initiatives: initiativeAddresses,
-          votes: new Array(initiativeAddresses.length).fill(0n) as bigint[],
-          vetos: new Array(initiativeAddresses.length).fill(0n) as bigint[],
+          votes: new Array<bigint>(initiativeAddresses.length).fill(0n),
+          vetos: new Array<bigint>(initiativeAddresses.length).fill(0n),
```
Comment (danielattilasimon) [inline frontend/app/src/tx-flows/allocateVotingPower.tsx:193]: Unrelated to the fix, but this is type-safer.

**Review by bpierre — APPROVED** [review]
Thanks @danielattilasimon :heart:
